/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SkillGapResult = IDL.Record({
  'readinessScore' : IDL.Nat,
  'recommendations' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'recommendedSkills' : IDL.Vec(IDL.Text),
  'missingSkills' : IDL.Vec(IDL.Text),
  'matchedSkills' : IDL.Vec(IDL.Text),
});
export const AnalysisRecord = IDL.Record({
  'result' : SkillGapResult,
  'resume' : IDL.Text,
  'jobDescription' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'analyzeSkillGap' : IDL.Func([IDL.Text, IDL.Text], [SkillGapResult], []),
  'getAnalysisHistory' : IDL.Func([], [IDL.Vec(AnalysisRecord)], ['query']),
  'saveAnalysis' : IDL.Func([IDL.Text, IDL.Text, SkillGapResult], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SkillGapResult = IDL.Record({
    'readinessScore' : IDL.Nat,
    'recommendations' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'recommendedSkills' : IDL.Vec(IDL.Text),
    'missingSkills' : IDL.Vec(IDL.Text),
    'matchedSkills' : IDL.Vec(IDL.Text),
  });
  const AnalysisRecord = IDL.Record({
    'result' : SkillGapResult,
    'resume' : IDL.Text,
    'jobDescription' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'analyzeSkillGap' : IDL.Func([IDL.Text, IDL.Text], [SkillGapResult], []),
    'getAnalysisHistory' : IDL.Func([], [IDL.Vec(AnalysisRecord)], ['query']),
    'saveAnalysis' : IDL.Func([IDL.Text, IDL.Text, SkillGapResult], [], []),
  });
};

export const init = ({ IDL }) => { return []; };